name: wepieces-next-db

services:
  database:
    image: postgres
    env_file: .env
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_SCHEMA}
    restart: always
    user: postgres
    volumes:
      - wepieces_next_db:/var/lib/postgresql/data
    ports:
      - "54323:5432"
    healthcheck:
      test: ["CMD", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4
    env_file: .env
    environment:
      PGADMIN_DEFAULT_EMAIL: ${SUPERADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${SUPERADMIN_PASSWORD}
    restart: always
    ports:
      - "5051:80"
    depends_on:
      - database
    volumes:
      - wepieces_next_admin:/var/lib/pgadmin

volumes:
  wepieces_next_db:
  wepieces_next_admin:
