import { ThemeProvider } from "@/components/theme-provider";
import { UserProvider } from "@/lib/auth";
import { getSafeUser } from "@/lib/auth/middleware";
import { cn } from "@/lib/utils";
import { GeistMono } from "geist/font/mono";
import { GeistSans } from "geist/font/sans";
import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  let userPromise = getSafeUser();

  return (
    <html
      lang='en'
      suppressHydrationWarning>
      <body
        className={cn(GeistSans.className, GeistMono.className, "antialiased")}>
        <ThemeProvider
          attribute='class'
          defaultTheme='system'
          enableSystem
          disableTransitionOnChange>
          <UserProvider userPromise={userPromise}>{children}</UserProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
